name: Deploy Astro site to Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "./site"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Install TeX
        run: |
          sudo apt update
          sudo apt install -y \
            texlive-latex-extra \
            texlive-bibtex-extra \
            biber \
            latexmk

      - name: create dummy figures dir
        run: mkdir -p tex/introduction-to-topological-manifolds/figures

      - name: notes-cli
        run: |
          go install github.com/samuelireson/notes-cli@latest
          notes-cli convert tex/introduction-to-topological-manifolds
          notes-cli compile tex/introduction-to-topological-manifolds

      - name: Build with Astro
        run: |
          npx --no-install astro build \
            --site "${{ steps.pages.outputs.origin }}" \
            --base "${{ steps.pages.outputs.base_path }}"
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

      - name: Commit back
        uses: stefanzweifel/git-auto-commit-action@v5

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
